import { MarkdownIt, Token } from '../@types/markdown-it';
import toc from 'markdown-it-table-of-contents';
import { slugify } from './shared';
import { config } from '../services/common/config';

/**
 * TOC Cache - stores generated TOC HTML keyed by heading structure hash.
 * This prevents expensive TOC regeneration when only non-heading content changes.
 */
interface TocCacheEntry {
    html: string;
    headingHash: string;
    timestamp: number;
}

const tocCache: Map<string, TocCacheEntry> = new Map();
const TOC_CACHE_MAX_AGE = 30000; // 30 seconds max cache age
const TOC_DEBOUNCE_MS = 1500; // 1.5 second debounce for heading changes

// Track last heading change time per document
const lastHeadingChange: Map<string, number> = new Map();

export function MarkdownItTOC(md: MarkdownIt) {
    // Add custom anchor renderer
    md.renderer.rules.tocAnchor = renderAnchor;

    // Add anchor injection rule
    md.core.ruler.push("tocAnchor", tocAnchorWorker);

    // Use the TOC plugin with caching wrapper
    md.use(toc, {
        slugify: slugify,
        includeLevel: config.tocLevels,
        containerHeaderHtml: '',
        listType: 'ul',
        // Custom container renderer that uses caching
        transformContainerOpen: () => '<nav class="table-of-contents">',
        transformContainerClose: () => '</nav>',
    });

    // Add caching rule that runs after TOC generation
    md.core.ruler.push("tocCache", createTocCacheRule(md));
}

function renderAnchor(tokens: Token[], idx: number): string {
    const token = tokens[idx];
    if (token.type !== "tocAnchor") return token.content;
    return `<a class="toc-anchor" id="${slugify(token.content)}"></a>`;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function tocAnchorWorker(state: any): void {
    const tokens: Token[] = [];
    state.tokens.forEach((t: Token, i: number, ts: Token[]) => {
        if (t.type === "heading_open") {
            const anchor = new state.Token("tocAnchor", "a", 0);
            anchor.content = ts[i + 1].content;
            tokens.push(anchor);
        }
        tokens.push(t);
    });
    state.tokens = tokens;
}

/**
 * Creates a caching rule for TOC generation.
 * Only regenerates TOC when heading structure changes and debounce period has passed.
 */
function createTocCacheRule(md: MarkdownIt) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return function tocCacheRule(state: any): void {
        const env = state.env || {};
        const docId = env.docId || 'default';

        // Extract heading structure
        const headings = extractHeadings(state.tokens);
        const headingHash = hashHeadings(headings);

        // Check cache
        const cached = tocCache.get(docId);
        const now = Date.now();

        if (cached && cached.headingHash === headingHash) {
            // Headings unchanged - use cache (no debounce needed)
            return;
        }

        // Headings changed - check debounce
        const lastChange = lastHeadingChange.get(docId) || 0;

        if (cached && (now - lastChange) < TOC_DEBOUNCE_MS) {
            // Still within debounce period - keep old TOC
            // This prevents TOC flickering while typing headings
            return;
        }

        // Record heading change time
        lastHeadingChange.set(docId, now);

        // Update cache with new heading hash
        // The actual TOC HTML is generated by the toc plugin
        tocCache.set(docId, {
            html: '', // We don't cache HTML directly, just track heading state
            headingHash: headingHash,
            timestamp: now,
        });

        // Clean old cache entries
        cleanCache();
    };
}

interface HeadingInfo {
    level: number;
    content: string;
}

function extractHeadings(tokens: Token[]): HeadingInfo[] {
    const headings: HeadingInfo[] = [];

    for (let i = 0; i < tokens.length; i++) {
        const token = tokens[i];
        if (token.type === 'heading_open') {
            const level = parseInt(token.tag.slice(1), 10);
            const contentToken = tokens[i + 1];
            if (contentToken && contentToken.type === 'inline') {
                headings.push({
                    level,
                    content: contentToken.content,
                });
            }
        }
    }

    return headings;
}

/**
 * Simple hash of heading structure for cache key comparison.
 */
function hashHeadings(headings: HeadingInfo[]): string {
    return headings.map(h => `${h.level}:${h.content}`).join('|');
}

/**
 * Clean expired cache entries.
 */
function cleanCache(): void {
    const now = Date.now();
    for (const [key, entry] of tocCache.entries()) {
        if (now - entry.timestamp > TOC_CACHE_MAX_AGE) {
            tocCache.delete(key);
            lastHeadingChange.delete(key);
        }
    }
}

/**
 * Clear the TOC cache - useful when document is closed.
 */
export function clearTocCache(docId?: string): void {
    if (docId) {
        tocCache.delete(docId);
        lastHeadingChange.delete(docId);
    } else {
        tocCache.clear();
        lastHeadingChange.clear();
    }
}
